    sum()
    count()
    max()
    min()
    mean()
    median()
    mode()
    std()
    describe()

In [1]:
import pandas as pd

dataset = {
    'Mathematics':[90,85,98,55,78,80],
    'Science':[92,87,95,86,90,81],
    "French":[49,41,48,37,48,30]

}

In [2]:
df = pd.DataFrame(data = dataset)
df.columns

Index(['Mathematics', 'Science', 'French'], dtype='str')

In [3]:
df.min()

Mathematics    55
Science        81
French         30
dtype: int64

In [4]:
df.max()

Mathematics    98
Science        95
French         49
dtype: int64

In [5]:
df.sum()

Mathematics    486
Science        531
French         253
dtype: int64

In [6]:
df.count()

Mathematics    6
Science        6
French         6
dtype: int64

In [7]:
df.mean()

Mathematics    81.000000
Science        88.500000
French         42.166667
dtype: float64

In [8]:
df.median()

Mathematics    82.5
Science        88.5
French         44.5
dtype: float64

In [9]:
df.mode() # it is the most frequent occuring number and hence French has only one vlaue

   Mathematics  Science  French
0           55       81    48.0
1           78       86     NaN
2           80       87     NaN
3           85       90     NaN
4           90       92     NaN
5           98       95     NaN

In [10]:
df.std()

Mathematics    14.642404
Science         4.929503
French          7.626707
dtype: float64

In [11]:
df.describe()

       Mathematics    Science     French
count     6.000000   6.000000   6.000000
mean     81.000000  88.500000  42.166667
std      14.642404   4.929503   7.626707
min      55.000000  81.000000  30.000000
25%      78.500000  86.250000  38.000000
50%      82.500000  88.500000  44.500000
75%      88.750000  91.500000  48.000000
max      98.000000  95.000000  49.000000